
export const TIPO_MENSAJE_ENTRADA =
{
    DATO_CONSTANTE: 1,
    CADENA_LIBRE: 2,
    CADENA_CON_PATRON: 3,
    ANALISIS_INTELIGENTE: 4,
    ECUACION_CON_VARIABLES: 5,
    IMAGEN: 6,
}

export const TIPO_ACCION =
{
    INVOCAR_SERVICIO_API: 1,
    ENVIAR_CORREO_ELECTRONICO: 2,
}


